### ISSUE TITLE
Travis build is failing

### ISSUE THREAD

**Issue by rs22** [osmhpi/cohydra#1]
The travis build configuration should be updated to match the updated example paths.

Also, the build badge could be added to the README:

[![Build Badge](https://api.travis-ci.com/osmhpi/cohydra.svg?branch=master)](https://travis-ci.com/osmhpi/cohydra)

**Comment by arneboockmeyer** [comment]
The docker-compose build `docker-compose build` in the `.travis.yml` is failing because there is no docker-compose file.

Steps to reproduce locally:
```
docker build -t testbed .
docker-compose build
```

**Comment by felix-gohla** [comment]
@mgjm plans to use DockerHub for building the containers. Otherwise, Travis would have to build ns-3 from scratch every time. But the service account does not work properly, he said. After fixing that, we could introduce proper tests.
