### ISSUE TITLE
Private Git Submodules

### ISSUE THREAD

**Issue by mgjm** [osmhpi/cohydra#20]
The submodules in `examples/docker/sumo/filetransfer` and `examples/docker/sumo/scenarios` are internal GitLab repositories of the HPI GitLab. Therefore the build on Docker Hub failed because they where unable to clone the internal submodules.

@arneboockmeyer Can you publish your `scenarios` and `filetransfer` program on GitHub or can we embed a copy of these files in this repository?

**Comment by arneboockmeyer** [comment]
Yes, I will do one of these options.
