### ISSUE TITLE
Ctrl-C in Simulation displays Exception

### ISSUE THREAD

**Issue by felix-gohla** [osmhpi/cohydra#9]
While running the simulation, you can abort the simulation with <kbd>Ctrl</kbd>+<kbd>C</kbd>. But after tearing down the simulation, it displays the `KeyboardInterrupt` Exception that triggered the stop. This seems a little annoying because it indicates that there was an error:

```python
Traceback (most recent call last):
  File "./basic_example.py", line 22, in <module>
    parser.run(main)
  File "/usr/local/lib/python3/dist-packages/testbed/argparse.py", line 57, in run
    main(**args)
  File "./basic_example.py", line 18, in main
    sim.simulate(simluation_time=60)
  File "/usr/local/lib/python3/dist-packages/testbed/simulation.py", line 193, in simulate
    thread.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

A **simple fix** would be to catch the `KeyboardInterrupt` in the simulation.

**Comment by arneboockmeyer** [comment]
I'm not sure if there is even a better way. I would be totally fine with that.

**Comment by felix-gohla** [comment]
What would be the better way? Just leaving it as it is?

My proposed solution would be inserting the following:
```diff
diff --git a/testbed/simulation.py b/testbed/simulation.py
index a93fb40..371b54f 100644
--- a/testbed/simulation.py
+++ b/testbed/simulation.py
@@ -191,6 +191,8 @@ class Simulation:
                 self.workflows.append(workflow)
                 workflow.start()
             thread.join()
+        except KeyboardInterrupt:
+            pass
         finally:
             # Stopping the workflows cannot be deferred, because
             # the deferred items won't be cleaned up, until workflows ended.
```

**Comment by lpirl** [comment]
> ```diff
> +        except KeyboardInterrupt:
> ```

Yes, this is how it's usually handled.

**Comment by arneboockmeyer** [comment]
No I think there is no better way. Thats how I would do it. Looks good 👍

**Comment by mgjm** [comment]
Should we only handle a `KeyboardInterrupt` during the simulation or also during the `prepare` step (which can take quite long when preparing a lot of nodes).

**Comment by lpirl** [comment]
Yes, the keyboard interrupt should be caught in whatever stage of the
execution it occurs.
You'd usually wrap the main CLI entry point with an exception handler.
